# Generated by Django 4.2.4 on 2023-08-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chathistory_chat_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
